[package]
name = "hyperliquid_rust_sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
ethers = {version = "0.17", features = ["eip712", "abigen"]}
hex = "0.4.3"
http = "0.2.9"
reqwest = {git = "https://github.com/seanmonstar/reqwest.git", rev = "61b1b2b"}
serde = {version = "1.0.175", features = ["derive"]}
serde_json = "1.0.103"
thiserror = "1.0.44"
tokio = {version = "1.29.1", features = ["full"]}
