[package]
name = "hyperliquid-rust-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "2.0.8"
reqwest = {git = "https://github.com/seanmonstar/reqwest.git", rev = "61b1b2b"}
serde = {version = "1.0.175", features = ["derive"]}
serde_json = "1.0.103"
tokio = {version = "1.29.1", features = ["full"]}
